### ISSUE TITLE
Trying to Import Add-on causes Traceback Error - unable to load

### ISSUE THREAD

**Issue by DR-Aeronautics** [BMCDad/orbiter-blender#18]
Received this error after trying to do step # 4 as specified in "README.md".

Traceback (most recent call last):
  File "E:\Custom Programs\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'orbiter-blender-2'

The module does not load in Blender 2.82 and I am unable to use it. In case this is useful, here are my paths:
Blender Install Location: E:\Custom Programs\Blender Foundation\Blender 2.82
Orbiter Location: E:\Carl\Documents\Orbiter2010
Add-on Download Location: C:\Users\Carl\Downloads\orbiter-blender-2.0.12.zip
Blender Installs the Add-on to: C:\Users\Carl\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\orbiter-blender-2.0.12

Please contact me with any questions. Any help is appreciated. I am trying to develop a heat shield meshfile in Orbiter.

**Comment by supersonic71** [comment]
Hi, I have the same problem. Were you able to find a solution?

**Comment by DR-Aeronautics** [comment]
No unfortunately. I learned how to stitch together various meshes to get what I wanted. Unfortunately that means I can't redistribute what I made. I hope BMCDad will show up at some point.

**Comment by BMCDad** [comment]
Sorry about that, Github is not notifying me of issues posted here.  Also, the published version I thought I had put up did not actually publish.

Please try downloading the latest release and then loading as indicated in the readme.  That should work.

I'm probably easier to reach on the orbiter forum as 'Blake'.

**Comment by DR-Aeronautics** [comment]
Awesome! I just got through the MyShip tutorial and it works! Glad to see the Orbiter modding community is still lively. Time for me to get started building balloons and heat shields! :)

**Comment by supersonic71** [comment]
Thank you, tried with Blender 3.0 a week ago and it works! (forgot to comment)
Trying to make a moon base :D
