### ISSUE TITLE
Wrong Exported Normals

### ISSUE THREAD

**Issue by Jordan-64** [BMCDad/orbiter-blender#22]
![Normals](https://github.com/BMCDad/orbiter-blender/assets/65469274/c9d99e0e-6e4d-4e4b-a08e-f1ed4b4fb295)

I noticed that the normals are not exported correctly. In Blender the mesh is displayed correctly but in Orbiter there are sometimes shading problems under certain viewing angles. This also causes noticeable problems with the effects in the new Sunlit Virtual Cockpit. When importing the mesh into Blender you will see that the normals do not match the original Blender file.

Here is the blend file for testing if you want
https://www.dropbox.com/s/e8pw9rn9hvgdoar/ECS.zip?dl=0

**Comment by Jordan-64** [comment]
It seems that the problem arises when the object is rotated, applying the rotation will solve it.

**Comment by BMCDad** [comment]
Thanks, 2.1.1 should address this issue.

**Comment by Jordan-64** [comment]
Thanks. I tested it briefly and it looks like it works perfect, I'll do some few more tests and close the issue as solved.
